name: simple_attendence_app
description: A simple app to generate attendence reports in pdf.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  path_provider: ^2.1.1
  pdf: ^3.10.4
  permission_handler: ^11.0.1
  printing: ^5.11.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.0
  

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  min_sdk_android: 21 